function [a1sol,zsol] = stst_barbarossa(u,in2)
%STST_BARBAROSSA
%    [A1SOL,ZSOL] = STST_BARBAROSSA(U,IN2)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:49

T = in2(9,:);
a2 = in2(2,:);
delta = in2(6,:);
gam = in2(5,:);
kappa1 = in2(3,:);
kappa2 = in2(4,:);
mu0 = in2(10,:);
tau1 = in2(7,:);
tau2 = in2(8,:);
t2 = T.*tau1;
t3 = T+u;
t4 = tau2.*u;
t5 = 1.0./t3;
t6 = t2+t4;
t7 = mu0.*t5.*t6;
t8 = exp(t7);
a1sol = (t8.*exp(kappa1.*u).*(gam.*u+delta.*u.^2).*(a2.*exp(-kappa2.*u).*exp(-mu0.*(tau1-t5.*u.*(tau1-tau2)))+1.0))./u;
if nargout > 1
    zsol = t8.*u.*(gam+delta.*u);
end
end
