function varargout=sym_barbarossa(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'npar'
   varargout{1}=10;
   return
  case 'tp_del'
   varargout{1}=1;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_barbarossa_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out1,out2] = sym_barbarossa_rhs_1_0(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_RHS_1_0
%    [OUT1,OUT2] = SYM_BARBAROSSA_RHS_1_0(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:44

t2 = T+u;
t3 = -tau2;
t4 = 1.0./t2;
t5 = t3+tau1;
t6 = t4.*t5.*u;
t7 = -t6;
t10 = mu0.*(t6-tau1);
t11 = exp(t10);
out1 = -(t11.*zt-u.*(gam+delta.*u))./(t11.*zt.*(t4.*t5+t4.*t7)-1.0);
if nargout > 1
    out2 = -z+a1.*u.*exp(-kappa1.*u)-a2.*t11.*zt.*exp(-kappa2.*u);
end
end


function [out1,out2] = sym_barbarossa_rhs_1_1(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_RHS_1_1
%    [OUT1,OUT2] = SYM_BARBAROSSA_RHS_1_1(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:44

t2 = T+u;
t3 = T_d+u_d;
t4 = delta.*u;
t5 = kappa1.*u;
t6 = kappa2.*u;
t7 = -tau2;
t8 = -tau2_d;
t9 = -t5;
t10 = -t6;
t11 = gam+t4;
t12 = 1.0./t2;
t16 = t7+tau1;
t17 = t8+tau1_d;
t13 = t12.^2;
t14 = exp(t9);
t15 = exp(t10);
t18 = t12.*t16;
t21 = t12.*t17.*u;
t19 = t18.*u;
t20 = t13.*t16.*u;
t22 = t18.*u_d;
t24 = -t20;
t31 = mu0.*(t19-tau1);
t32 = exp(t31);
t33 = t18+t24;
t36 = t32.*t33.*zt;
t37 = t36-1.0;
out1 = (u.*(gam_d+delta_d.*u+delta.*u_d)+t11.*u_d-t32.*zt_d-t32.*zt.*(mu0.*(t21+t22-tau1_d+t3.*t24)+mu0_d.*(t19-tau1)))./t37-1.0./t37.^2.*(t11.*u-t32.*zt).*(t36.*(mu0.*(t21+t22-tau1_d+t3.*t24)+mu0_d.*(t19-tau1))-t32.*zt.*(-t12.*t17-t3.*t12.^2.*t19.*2.0+t3.*t13.*t16+t13.*t17.*u+t13.*t16.*u_d)+t32.*t33.*zt_d);
if nargout > 1
    out2 = -z_d+a1_d.*t14.*u+a1.*t14.*u_d-a2.*t15.*t32.*zt_d-a2_d.*t15.*t32.*zt-a1.*t14.*u.*(kappa1_d.*u+kappa1.*u_d)+a2.*t15.*t32.*zt.*(kappa2_d.*u+kappa2.*u_d)-a2.*t15.*t32.*zt.*(mu0.*(t21+t22-tau1_d+t3.*t24)+mu0_d.*(t19-tau1));
end
end


function [out1,out2] = sym_barbarossa_rhs_1_2(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_RHS_1_2
%    [OUT1,OUT2] = SYM_BARBAROSSA_RHS_1_2(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:44

t2 = T+u;
t3 = T_d+u_d;
t4 = delta.*u;
t5 = delta_d.*u;
t6 = delta.*u_d;
t7 = kappa1.*u;
t8 = kappa2.*u;
t9 = kappa1_d.*u;
t10 = kappa2_d.*u;
t11 = kappa1.*u_d;
t12 = kappa2.*u_d;
t13 = -tau2;
t14 = -tau2_d;
t15 = -t7;
t16 = -t8;
t17 = t3.^2;
t18 = gam+t4;
t19 = 1.0./t2;
t24 = t13+tau1;
t25 = t14+tau1_d;
t27 = t9+t11;
t28 = t10+t12;
t29 = gam_d+t5+t6;
t20 = t19.^2;
t21 = t19.^3;
t22 = exp(t15);
t23 = exp(t16);
t26 = t18.*u;
t30 = t19.*t24;
t31 = t19.*t25;
t32 = t30.*u;
t33 = t20.*t24.*u;
t34 = t31.*u;
t35 = t20.*t25.*u;
t36 = t30.*u_d;
t37 = t20.*t24.*u_d;
t38 = t31.*u_d.*2.0;
t39 = -t31;
t44 = t3.*t20.*t24;
t46 = t3.*t21.*t24.*u.*2.0;
t53 = t17.*t21.*t24.*u.*2.0;
t41 = -t33;
t47 = t3.*t35.*2.0;
t48 = t3.*t37.*2.0;
t50 = -t46;
t56 = mu0.*(t32-tau1);
t51 = -t47;
t52 = -t48;
t57 = exp(t56);
t60 = t30+t41;
t65 = mu0_d.*(t34+t36-tau1_d+t3.*t41).*2.0;
t74 = (mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1)).^2;
t75 = t35+t37+t39+t44+t50;
t58 = t57.*zt;
t67 = t57.*t60.*zt_d;
t71 = t38+t51+t52+t53;
t59 = -t58;
t66 = t58.*t60;
t73 = mu0.*t71;
t76 = t58.*t75;
t61 = t26+t59;
t69 = t66-1.0;
t78 = t65+t73;
t70 = 1.0./t69.^2;
et1 = -(t58.*t74+t58.*t78-t5.*u_d.*2.0-t29.*u_d.*2.0+t57.*zt_d.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1)).*2.0)./t69+t61.*t70.*(t58.*(t3.*t20.*t25.*2.0-t17.*t21.*t24.*2.0+t17.*t20.*t33.*6.0+t20.*t25.*u_d.*2.0-t3.*t21.*t25.*u.*4.0-t3.*t21.*t24.*u_d.*4.0)-t67.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1)).*2.0+t76.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1)).*2.0+t59.*t60.*t74+t59.*t60.*t78+t57.*t75.*zt_d.*2.0);
et2 = t70.*(t67+t59.*t75+t66.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1))).*(t29.*u+t18.*u_d-t57.*zt_d+t59.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1))).*-2.0+t61.*1.0./t69.^3.*(t67+t59.*t75+t66.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1))).^2.*2.0;
out1 = et1+et2;
if nargout > 1
    out2 = a1_d.*t22.*u_d.*2.0+a2.*t23.*t59.*t74+a2.*t23.*t59.*t78+a2_d.*t23.*t28.*t58.*2.0-a1_d.*t22.*t27.*u.*2.0-a1.*t9.*t22.*u_d.*2.0-a1.*t22.*t27.*u_d.*2.0-a2_d.*t23.*t57.*zt_d.*2.0+a2.*t23.*t28.^2.*t59+a1.*t22.*t27.^2.*u-a2_d.*t23.*t58.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1)).*2.0+a2.*t23.*t28.*t58.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1)).*2.0-a2.*t23.*t57.*zt_d.*(mu0.*(t34+t36-tau1_d+t3.*t41)+mu0_d.*(t32-tau1)).*2.0+a2.*kappa2_d.*t23.*t58.*u_d.*2.0+a2.*t23.*t28.*t57.*zt_d.*2.0;
end
end


function [out1,out2] = sym_barbarossa_rhs_1_3(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_RHS_1_3
%    [OUT1,OUT2] = SYM_BARBAROSSA_RHS_1_3(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:45

t2 = T+u;
t3 = T_d+u_d;
t4 = delta.*u;
t5 = delta_d.*u;
t6 = delta.*u_d;
t7 = kappa1.*u;
t8 = kappa2.*u;
t9 = kappa1_d.*u;
t10 = kappa2_d.*u;
t11 = kappa1.*u_d;
t12 = kappa2.*u_d;
t13 = u_d.^2;
t14 = -tau2;
t15 = -tau2_d;
t16 = -t7;
t17 = -t8;
t18 = t3.^2;
t19 = t3.^3;
t20 = gam+t4;
t21 = 1.0./t2;
t27 = t14+tau1;
t28 = t15+tau1_d;
t31 = t9+t11;
t32 = t10+t12;
t33 = gam_d+t5+t6;
t22 = t21.^2;
t23 = t21.^3;
t25 = exp(t16);
t26 = exp(t17);
t29 = t20.*u;
t30 = t20.*u_d;
t34 = t31.^2;
t35 = t32.^2;
t36 = t33.*u;
t37 = t21.*t27;
t38 = t21.*t28;
t24 = t22.^2;
t39 = t37.*u;
t40 = t22.*t27.*u;
t41 = t38.*u;
t42 = t22.*t28.*u;
t43 = t37.*u_d;
t44 = t22.*t27.*u_d;
t45 = t38.*u_d.*2.0;
t46 = t22.*t28.*u_d.*2.0;
t47 = -t38;
t52 = t3.*t22.*t27;
t54 = t3.*t22.*t28.*2.0;
t55 = t3.*t23.*t27.*u.*2.0;
t57 = t3.*t23.*t28.*u.*4.0;
t59 = t3.*t23.*t27.*u_d.*4.0;
t60 = t3.*t22.*t28.*u_d.*6.0;
t62 = t18.*t23.*t27.*2.0;
t72 = t18.*t23.*t28.*u.*6.0;
t73 = t18.*t23.*t27.*u_d.*6.0;
t49 = -t40;
t56 = t3.*t42.*2.0;
t58 = t3.*t44.*2.0;
t63 = -t55;
t65 = -t57;
t67 = -t59;
t68 = -t62;
t69 = t62.*u;
t70 = t18.*t24.*t27.*u.*6.0;
t71 = t19.*t24.*t27.*u.*6.0;
t76 = -t72;
t77 = -t73;
t78 = mu0.*(t39-tau1);
t64 = -t56;
t66 = -t58;
t79 = exp(t78);
t84 = t37+t49;
t89 = mu0_d.*(t41+t43-tau1_d+t3.*t49).*2.0;
t99 = (mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).^2;
t102 = t42+t44+t47+t52+t63;
t103 = t60+t71+t76+t77;
t109 = t46+t54+t65+t67+t68+t70;
t80 = t79.*zt;
t81 = t79.*zt_d;
t96 = t45+t64+t66+t69;
t104 = mu0.*t103;
t82 = -t80;
t83 = -t81;
t90 = t80.*t84;
t91 = t81.*t84;
t98 = mu0.*t96;
t101 = mu0_d.*t96.*3.0;
t105 = -t104;
t107 = t80.*t102;
t108 = t81.*t102.*2.0;
t115 = t80.*t109;
t85 = t29+t82;
t93 = t90-1.0;
t106 = t82.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1));
t111 = t91.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*-2.0;
t113 = t89+t98;
t114 = t82.*t84.*t99;
t117 = t101+t105;
t119 = t107.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*2.0;
t94 = 1.0./t93.^2;
t95 = 1.0./t93.^3;
t110 = t84.*t106;
t116 = t30+t36+t83+t106;
t120 = t90.*t113;
t121 = t82.*t84.*t113;
t123 = t108+t111+t114+t115+t119+t121;
et1 = -(t80.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).^3-delta_d.*t13.*6.0+t81.*t99.*3.0+t81.*t113.*3.0-t82.*t117+t80.*t113.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*3.0)./t93+t94.*(t91+t82.*t102+t90.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1))).*(t80.*t99+t80.*t113-t5.*u_d.*2.0-t33.*u_d.*2.0+t81.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*2.0).*3.0+t95.*t116.*(t91+t82.*t102+t90.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1))).^2.*6.0+t94.*t116.*t123.*3.0;
et2 = t85.*t94.*(t110.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).^2+t81.*t109.*3.0-t91.*t99.*3.0-t91.*t113.*3.0+t99.*t107.*3.0-t90.*t117+t107.*t113.*3.0+t82.*(t19.*t21.^4.*t39.*2.4e+1+t18.*t23.*t28.*6.0-t19.*t24.*t27.*6.0-t18.*t24.*t28.*u.*1.8e+1+t3.*t23.*t28.*u_d.*1.2e+1-t18.*t24.*t27.*u_d.*1.8e+1)+t115.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*3.0-t120.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*3.0+t81.*t102.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*6.0);
et3 = t85.*t94.^2.*(t91+t82.*t102+t90.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1))).^3.*-6.0-t85.*t95.*t123.*(t91+t82.*t102+t90.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1))).*6.0;
out1 = et1+et2+et3;
if nargout > 1
    et4 = a2.*t26.*t106.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).^2-a1.*kappa1_d.*t13.*t25.*6.0-a2.*t26.*t35.*t81.*3.0-a2.*t26.*t81.*t99.*3.0-a2.*t26.*t81.*t113.*3.0-a2.*t26.*t80.*t117+a2_d.*t26.*t32.*t81.*6.0-a2_d.*t26.*t35.*t80.*3.0-a2_d.*t26.*t80.*t99.*3.0-a2_d.*t26.*t80.*t113.*3.0+a1_d.*t25.*t34.*u.*3.0+a1.*t25.*t34.*u_d.*3.0-a1_d.*t9.*t25.*u_d.*6.0-a1_d.*t25.*t31.*u_d.*6.0+a2.*t26.*t32.^3.*t80-a1.*t25.*t31.^3.*u-a2_d.*t26.*t81.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*6.0+a2.*t26.*t32.*t81.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*6.0;
    et5 = a2.*t26.*t35.*t80.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*-3.0-a2.*t26.*t80.*t113.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*3.0+a2_d.*t26.*t32.*t80.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*6.0+a2.*kappa2_d.*t26.*t81.*u_d.*6.0+a2_d.*kappa2_d.*t26.*t80.*u_d.*6.0+a2.*t26.*t32.*t80.*t99.*3.0+a2.*t26.*t32.*t80.*t113.*3.0+a1.*t9.*t25.*t31.*u_d.*6.0+a2.*kappa2_d.*t26.*t80.*u_d.*(mu0.*(t41+t43-tau1_d+t3.*t49)+mu0_d.*(t39-tau1)).*6.0-a2.*kappa2_d.*t26.*t32.*t80.*u_d.*6.0;
    out2 = et4+et5;
end
end


function [out1,out2] = sym_barbarossa_rhs_1_4(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_RHS_1_4
%    [OUT1,OUT2] = SYM_BARBAROSSA_RHS_1_4(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:45

t2 = T+u;
t3 = T_d+u_d;
t4 = delta.*u;
t5 = delta_d.*u;
t6 = delta.*u_d;
t7 = kappa1.*u;
t8 = kappa2.*u;
t9 = kappa1_d.*u;
t10 = kappa2_d.*u;
t11 = kappa1.*u_d;
t12 = kappa2.*u_d;
t13 = u_d.^2;
t14 = -tau2;
t15 = -tau2_d;
t16 = -t7;
t17 = -t8;
t18 = t3.^2;
t19 = t3.^3;
t21 = t5.*u_d.*2.0;
t22 = gam+t4;
t23 = 1.0./t2;
t30 = t14+tau1;
t31 = t15+tau1_d;
t34 = t9+t11;
t35 = t10+t12;
t36 = gam_d+t5+t6;
t20 = t18.^2;
t24 = t23.^2;
t25 = t23.^3;
t27 = t23.^5;
t28 = exp(t16);
t29 = exp(t17);
t32 = t22.*u;
t33 = t22.*u_d;
t37 = t34.^2;
t38 = t34.^3;
t39 = t35.^2;
t40 = t35.^3;
t41 = t36.*u;
t42 = t36.*u_d.*2.0;
t43 = t23.*t30;
t44 = t23.*t31;
t26 = t24.^2;
t45 = t43.*u;
t46 = t24.*t30.*u;
t47 = t44.*u;
t48 = t24.*t31.*u;
t49 = t43.*u_d;
t50 = t24.*t30.*u_d;
t51 = t44.*u_d.*2.0;
t52 = t24.*t31.*u_d.*2.0;
t53 = -t44;
t58 = t3.*t24.*t30;
t60 = t3.*t24.*t31.*2.0;
t61 = t3.*t25.*t30.*u.*2.0;
t63 = t3.*t25.*t31.*u.*4.0;
t65 = t3.*t25.*t30.*u_d.*4.0;
t66 = t3.*t24.*t31.*u_d.*6.0;
t68 = t18.*t25.*t30.*2.0;
t70 = t18.*t25.*t31.*6.0;
t76 = t3.*t25.*t31.*u_d.*1.2e+1;
t84 = t18.*t25.*t30.*u_d.*6.0;
t87 = t19.*t27.*t30.*u.*2.4e+1;
t88 = t20.*t27.*t30.*u.*2.4e+1;
t89 = t18.*t25.*t31.*u.*-6.0;
t95 = t18.*t25.*t31.*u_d.*2.4e+1;
t55 = -t46;
t62 = t3.*t48.*2.0;
t64 = t3.*t50.*2.0;
t69 = t19.*t26.*t30.*6.0;
t71 = -t61;
t73 = -t63;
t75 = -t65;
t77 = -t68;
t78 = -t70;
t79 = -t76;
t80 = t68.*u;
t81 = t18.*t26.*t30.*u.*6.0;
t90 = t18.*t26.*t31.*u.*1.8e+1;
t91 = t19.*t26.*t31.*u.*2.4e+1;
t92 = -t84;
t93 = t18.*t26.*t30.*u_d.*1.8e+1;
t94 = t19.*t26.*t30.*u_d.*2.4e+1;
t96 = -t87;
t99 = mu0.*(t45-tau1);
t72 = -t62;
t74 = -t64;
t82 = t69.*u;
t97 = -t91;
t98 = -t94;
t100 = exp(t99);
t105 = t43+t55;
t110 = mu0_d.*(t47+t49-tau1_d+t3.*t55).*2.0;
t121 = (mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^2;
t125 = t48+t50+t53+t58+t71;
t139 = t52+t60+t73+t75+t77+t81;
t140 = t69+t78+t79+t90+t93+t96;
t101 = t100.*zt;
t102 = t100.*zt_d;
t118 = t51+t72+t74+t80;
t123 = t121.^2;
t126 = t66+t82+t89+t92;
t131 = t88+t95+t97+t98;
t103 = -t101;
t104 = -t102;
t111 = t101.*t105;
t112 = t102.*t105;
t120 = mu0.*t118;
t124 = mu0_d.*t118.*3.0;
t127 = mu0.*t126;
t128 = mu0_d.*t126.*4.0;
t132 = mu0.*t131;
t135 = t101.*t121;
t137 = t101.*t125;
t138 = t102.*t125.*2.0;
t150 = t101.*t139;
t151 = t102.*t139.*3.0;
t153 = t101.*t140;
t161 = t102.*t125.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*6.0;
t106 = t32+t103;
t114 = t111-1.0;
t129 = -t127;
t133 = t103.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1));
t136 = t103.*t121;
t142 = t112.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*-2.0;
t143 = t111.*t121;
t145 = t112.*t121.*3.0;
t146 = t110+t120;
t160 = t137.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*2.0;
t162 = t125.*t135.*3.0;
t168 = t150.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*3.0;
t174 = (t112+t103.*t125+t111.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1))).^2;
t115 = 1.0./t114.^2;
t116 = 1.0./t114.^3;
t141 = t105.*t133;
t147 = t105.*t136;
t148 = -t145;
t149 = t146.^2;
t152 = t33+t41+t104+t133;
t154 = t101.*t146;
t155 = t103.*t146;
t156 = t124+t129;
t163 = t111.*t146;
t164 = t112.*t146.*3.0;
t171 = t137.*t146.*3.0;
t117 = t115.^2;
t144 = t141.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^2;
t165 = t105.*t155;
t166 = -t164;
t170 = -t111.*t156;
t172 = t163.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*-3.0;
t176 = t138+t142+t147+t150+t160+t165;
t177 = t144+t148+t151+t153+t161+t162+t166+t168+t170+t171+t172;
et1 = t112.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^3.*-4.0+t137.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^3.*4.0+t102.*t140.*4.0-t111.*t149.*3.0-t112.*t156.*4.0+t135.*t139.*6.0-t143.*t146.*6.0+t137.*t156.*4.0+t146.*t150.*6.0+t101.*(t20.*t24.^2.*t46.*1.2e+2+t19.*t26.*t31.*2.4e+1-t20.*t27.*t30.*2.4e+1-t19.*t27.*t31.*u.*9.6e+1+t18.*t26.*t31.*u_d.*7.2e+1-t19.*t27.*t30.*u_d.*9.6e+1)+t153.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*4.0+t102.*t139.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*1.2e+1;
et2 = t112.*t146.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*-1.2e+1-t111.*t156.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*4.0+t137.*t146.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*1.2e+1+t103.*t105.*t123+t102.*t121.*t125.*1.2e+1+t102.*t125.*t146.*1.2e+1-t103.*t105.*(t128-t132);
et3 = -(t102.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^3.*4.0+t101.*t123+t101.*t149.*3.0+t102.*t156.*4.0+t135.*t146.*6.0-t101.*(t128-t132)+t102.*t146.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*1.2e+1+t101.*t156.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*4.0)./t114-t116.*t174.*(-t21-t42+t135+t154+t102.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*2.0).*1.2e+1-t115.*t176.*(-t21-t42+t135+t154+t102.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*2.0).*6.0+t106.*t116.*t176.^2.*6.0;
et4 = t115.*(t112+t103.*t125+t111.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1))).*(t101.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^3-delta_d.*t13.*6.0+t102.*t121.*3.0+t102.*t146.*3.0-t103.*t156+t154.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*3.0).*4.0+t106.*1.0./t114.^5.*t174.^2.*2.4e+1+t106.*t115.*(et1+et2)-t117.*t152.*(t112+t103.*t125+t111.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1))).^3.*2.4e+1+t115.*t152.*t177.*4.0+t106.*t117.*t174.*t176.*3.6e+1-t106.*t116.*t177.*(t112+t103.*t125+t111.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1))).*8.0;
et5 = t116.*t152.*t176.*(t112+t103.*t125+t111.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1))).*-2.4e+1;
out1 = et3+et4+et5;
if nargout > 1
    et6 = a2.*t29.*t102.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^3.*-4.0-a2_d.*t29.*t101.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^3.*4.0-a1_d.*kappa1_d.*t13.*t28.*2.4e+1+a2.*t29.*t40.*t102.*4.0-a2.*t29.*t39.*t135.*6.0-a2.*t29.*t39.*t154.*6.0+a2.*t29.*t103.*t123-a2.*t29.*t101.*t149.*3.0-a2.*t29.*t102.*t156.*4.0-a2.*t29.*t135.*t146.*6.0-a2_d.*t29.*t39.*t102.*1.2e+1+a2_d.*t29.*t40.*t101.*4.0+a2_d.*t29.*t35.*t135.*1.2e+1+a2_d.*t29.*t35.*t154.*1.2e+1-a2_d.*t29.*t102.*t121.*1.2e+1-a2_d.*t29.*t102.*t146.*1.2e+1-a2_d.*t29.*t101.*t156.*4.0-a1_d.*t28.*t38.*u.*4.0-a1.*t28.*t38.*u_d.*4.0+a1_d.*t28.*t37.*u_d.*1.2e+1-a2.*t29.*t103.*(t128-t132);
    et7 = a2.*t29.*t39.^2.*t103+a1.*t28.*t37.^2.*u-a2_d.*t29.*t154.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*1.2e+1-a2.*t29.*t39.*t102.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*1.2e+1+a2.*t29.*t40.*t101.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*4.0+a2.*t29.*t35.*t154.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*1.2e+1-a2.*t29.*t102.*t146.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*1.2e+1-a2.*t29.*t101.*t156.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*4.0;
    et8 = a2_d.*t29.*t35.*t102.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*2.4e+1-a2_d.*t29.*t39.*t101.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*1.2e+1+a2.*t29.*t35.*t101.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).^3.*4.0+a1.*kappa1_d.*t9.*t13.*t28.*1.2e+1+a1.*kappa1_d.*t13.*t28.*t34.*2.4e+1+a2.*kappa2_d.*t29.*t135.*u_d.*1.2e+1+a2.*kappa2_d.*t29.*t154.*u_d.*1.2e+1+a2_d.*kappa2_d.*t29.*t102.*u_d.*2.4e+1+a2.*t29.*t35.*t102.*t121.*1.2e+1+a2.*t29.*t35.*t102.*t146.*1.2e+1+a2.*t29.*t35.*t101.*t156.*4.0-a1.*t9.*t28.*t37.*u_d.*1.2e+1+a1_d.*t9.*t28.*t34.*u_d.*2.4e+1-a2.*kappa2_d.^2.*t13.*t29.*t101.*1.2e+1;
    et9 = a2.*kappa2_d.*t29.*t102.*u_d.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*2.4e+1+a2_d.*kappa2_d.*t29.*t101.*u_d.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*2.4e+1-a2.*kappa2_d.*t29.*t35.*t102.*u_d.*2.4e+1+a2.*kappa2_d.*t29.*t39.*t101.*u_d.*1.2e+1-a2_d.*kappa2_d.*t29.*t35.*t101.*u_d.*2.4e+1-a2.*kappa2_d.*t29.*t35.*t101.*u_d.*(mu0.*(t47+t49-tau1_d+t3.*t55)+mu0_d.*(t45-tau1)).*2.4e+1;
    out2 = et6+et7+et8+et9;
end
end


function [out1,out2] = sym_barbarossa_rhs_1_5(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_RHS_1_5
%    [OUT1,OUT2] = SYM_BARBAROSSA_RHS_1_5(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:46

t2 = T+u;
t3 = T_d+u_d;
t4 = delta.*u;
t5 = delta_d.*u;
t6 = delta.*u_d;
t7 = kappa1.*u;
t8 = kappa2.*u;
t9 = kappa1_d.*u;
t10 = kappa2_d.*u;
t11 = kappa1.*u_d;
t12 = kappa2.*u_d;
t13 = kappa1_d.^2;
t14 = kappa2_d.^2;
t15 = u_d.^2;
t16 = -tau2;
t17 = -tau2_d;
t18 = -t7;
t19 = -t8;
t20 = t3.^2;
t21 = t3.^3;
t23 = t3.^5;
t24 = t5.*u_d.*2.0;
t25 = gam+t4;
t26 = 1.0./t2;
t32 = delta_d.*t15.*6.0;
t35 = t16+tau1;
t36 = t17+tau1_d;
t39 = t9+t11;
t40 = t10+t12;
t41 = gam_d+t5+t6;
t22 = t20.^2;
t27 = t26.^2;
t28 = t26.^3;
t30 = t26.^5;
t33 = exp(t18);
t34 = exp(t19);
t37 = t25.*u;
t38 = t25.*u_d;
t42 = t39.^2;
t43 = t39.^3;
t45 = t40.^2;
t46 = t40.^3;
t48 = t41.*u;
t49 = t41.*u_d.*2.0;
t50 = t26.*t35;
t51 = t26.*t36;
t29 = t27.^2;
t31 = t27.^3;
t44 = t42.^2;
t47 = t45.^2;
t52 = t50.*u;
t53 = t27.*t35.*u;
t54 = t51.*u;
t55 = t27.*t36.*u;
t56 = t50.*u_d;
t57 = t27.*t35.*u_d;
t58 = t51.*u_d.*2.0;
t59 = t27.*t36.*u_d.*2.0;
t60 = -t51;
t65 = t3.*t27.*t35;
t67 = t3.*t27.*t36.*2.0;
t68 = t3.*t28.*t35.*u.*2.0;
t70 = t3.*t28.*t36.*u.*4.0;
t72 = t3.*t28.*t35.*u_d.*4.0;
t73 = t3.*t27.*t36.*u_d.*6.0;
t75 = t20.*t28.*t35.*2.0;
t77 = t20.*t28.*t36.*6.0;
t83 = t3.*t28.*t36.*u_d.*1.2e+1;
t85 = t22.*t30.*t35.*2.4e+1;
t93 = t20.*t28.*t35.*u_d.*6.0;
t97 = t21.*t30.*t35.*u.*2.4e+1;
t99 = t20.*t28.*t36.*u.*-6.0;
t105 = t20.*t28.*t36.*u_d.*2.4e+1;
t110 = t21.*t30.*t36.*u.*9.6e+1;
t111 = t22.*t30.*t36.*u.*1.2e+2;
t113 = t21.*t30.*t35.*u_d.*9.6e+1;
t114 = t22.*t30.*t35.*u_d.*1.2e+2;
t62 = -t53;
t69 = t3.*t55.*2.0;
t71 = t3.*t57.*2.0;
t76 = t21.*t29.*t35.*6.0;
t78 = -t68;
t80 = -t70;
t82 = -t72;
t84 = -t75;
t86 = -t77;
t87 = t21.*t29.*t36.*2.4e+1;
t88 = -t83;
t89 = t75.*u;
t90 = t20.*t29.*t35.*u.*6.0;
t100 = t20.*t29.*t36.*u.*1.8e+1;
t102 = -t93;
t103 = t20.*t29.*t35.*u_d.*1.8e+1;
t104 = t21.*t29.*t35.*u_d.*2.4e+1;
t106 = -t97;
t107 = t22.*t31.*t35.*u.*1.2e+2;
t108 = t23.*t31.*t35.*u.*1.2e+2;
t115 = t20.*t29.*t36.*u_d.*7.2e+1;
t116 = t21.*t29.*t36.*u_d.*1.2e+2;
t117 = mu0.*(t52-tau1);
t120 = -t111;
t121 = -t114;
t79 = -t69;
t81 = -t71;
t91 = t76.*u;
t96 = -t87;
t101 = t87.*u;
t118 = exp(t117);
t119 = -t107;
t122 = -t115;
t127 = t50+t62;
t132 = mu0_d.*(t54+t56-tau1_d+t3.*t62).*2.0;
t144 = (mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^2;
t149 = t55+t57+t60+t65+t78;
t158 = t108+t116+t120+t121;
t170 = t59+t67+t80+t82+t84+t90;
t171 = t76+t86+t88+t100+t103+t106;
t123 = t118.*zt;
t124 = t118.*zt_d;
t141 = t58+t79+t81+t89;
t146 = t144.^2;
t150 = t73+t91+t99+t102;
t159 = mu0.*t158;
t180 = t85+t96+t110+t113+t119+t122;
t125 = -t123;
t126 = -t124;
t133 = t123.*t127;
t134 = t124.*t127;
t143 = mu0.*t141;
t148 = mu0_d.*t141.*3.0;
t151 = mu0.*t150;
t152 = mu0_d.*t150.*4.0;
t163 = t123.*t144;
t165 = t124.*t144.*3.0;
t168 = t123.*t149;
t169 = t124.*t149.*2.0;
t185 = t123.*t170;
t186 = t124.*t170.*3.0;
t188 = t123.*t171;
t189 = t124.*t171.*4.0;
t192 = t123.*t180;
t201 = t124.*t149.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*6.0;
t204 = t124.*t144.*t149.*1.2e+1;
t128 = t37+t125;
t136 = t133-1.0;
t153 = -t151;
t161 = t125.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1));
t166 = t125.*t144;
t173 = t134.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*-2.0;
t174 = t133.*t144;
t177 = t134.*t144.*3.0;
t178 = t134.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*-4.0;
t179 = t132+t143;
t200 = t168.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0;
t202 = t149.*t163.*3.0;
t215 = t185.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*3.0;
t217 = t163.*t170.*6.0;
t237 = (t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).^2;
t137 = 1.0./t136.^2;
t138 = 1.0./t136.^3;
t140 = 1.0./t136.^5;
t164 = t161.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^2;
t181 = t127.*t166;
t182 = -t177;
t184 = t179.^2;
t187 = t38+t48+t126+t161;
t191 = t123.*t179;
t193 = t124.*t179.*3.0;
t194 = t125.*t179;
t196 = t148+t153;
t207 = t133.*t179;
t208 = t134.*t179.*3.0;
t225 = t168.*t179.*3.0;
t226 = t124.*t149.*t179.*1.2e+1;
t229 = t134.*t179.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*-1.2e+1;
t230 = t174.*t179.*6.0;
t234 = t179.*t185.*6.0;
t139 = t137.^2;
t175 = t127.*t164;
t209 = -t125.*t196;
t210 = t127.*t194;
t211 = -t208;
t213 = t133.*t184.*3.0;
t220 = t134.*t196.*4.0;
t221 = -t133.*t196;
t228 = t207.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*-3.0;
t232 = t168.*t196.*4.0;
t239 = t133.*t196.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*-4.0;
t244 = t169+t173+t181+t185+t200+t210;
t246 = t175+t182+t186+t188+t201+t202+t211+t215+t221+t225+t228;
t245 = t244.^2;
et1 = t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^5+t191.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*1.0e+1+t124.*t146.*5.0+t124.*t184.*1.5e+1+t163.*t196.*1.0e+1+t191.*t196.*1.0e+1-t124.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*5.0+t125.*(t159+mu0_d.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1).*5.0)+t123.*t184.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.5e+1+t124.*t196.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1+t124.*t144.*t179.*3.0e+1;
et2 = t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*-5.0;
et3 = t175.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^2+t185.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*1.0e+1-t207.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*1.0e+1-t134.*t146.*5.0-t124.*t180.*5.0+t146.*t168.*5.0-t134.*t184.*1.5e+1+t163.*t171.*1.0e+1+t168.*t184.*1.5e+1+t179.*t188.*1.0e+1-t174.*t196.*1.0e+1+t185.*t196.*1.0e+1-t196.*t207.*1.0e+1+t125.*(t23.*t26.^6.*t52.*7.2e+2+t22.*t30.*t36.*1.2e+2-t23.*t31.*t35.*1.2e+2-t22.*t31.*t36.*u.*6.0e+2+t21.*t30.*t36.*u_d.*4.8e+2-t22.*t31.*t35.*u_d.*6.0e+2);
et4 = t134.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*5.0-t168.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*5.0+t133.*(t159+mu0_d.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1).*5.0)-t192.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*5.0+t124.*t171.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1-t133.*t184.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.5e+1-t134.*t196.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1+t168.*t196.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1;
et5 = t179.*t185.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*3.0e+1+t124.*t149.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*2.0e+1+t124.*t144.*t170.*3.0e+1-t134.*t144.*t179.*3.0e+1+t124.*t149.*t196.*2.0e+1+t124.*t170.*t179.*3.0e+1+t149.*t163.*t179.*3.0e+1+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*5.0+t124.*t149.*t179.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*6.0e+1;
et6 = -(et1+et2)./t136-t137.*t246.*(-t24-t49+t163+t191+t124.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0).*1.0e+1+t140.*t187.*t237.^2.*1.2e+2;
et7 = t137.*t187.*(t178+t189+t204-t213+t217-t220+t226+t229-t230+t232+t234+t239+t168.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*4.0+t125.*t180+t133.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1))+t188.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*4.0+t124.*t170.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.2e+1+t168.*t179.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.2e+1+t125.*t127.*t146).*5.0+t138.*t187.*t245.*3.0e+1+t128.*t137.*(et3+et4+et5);
et8 = t137.*(t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).*(t124.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*4.0+t123.*t146+t123.*t184.*3.0+t124.*t196.*4.0+t163.*t179.*6.0+t125.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1))+t124.*t179.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.2e+1+t123.*t196.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*4.0).*5.0;
et9 = t138.*t237.*(-t32+t165+t193+t209+t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3+t191.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*3.0).*-2.0e+1-t137.*t244.*(-t32+t165+t193+t209+t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3+t191.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*3.0).*1.0e+1+t139.*(t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).^3.*(-t24-t49+t163+t191+t124.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0).*6.0e+1;
et10 = t128.*t137.^3.*(t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).^5.*-1.2e+2-t128.*t140.*t244.*(t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).^3.*2.4e+2+t128.*t139.*t237.*t246.*6.0e+1+t128.*t138.*t244.*t246.*2.0e+1+t139.*t187.*t237.*t244.*1.8e+2;
et11 = t128.*t138.*(t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).*(t178+t189+t204-t213+t217-t220+t226+t229-t230+t232+t234+t239+t168.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*4.0+t125.*t180+t133.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1))+t188.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*4.0+t124.*t170.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.2e+1+t168.*t179.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.2e+1+t125.*t127.*t146).*-1.0e+1;
et12 = t128.*t139.*t245.*(t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).*-9.0e+1-t138.*t187.*t246.*(t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).*4.0e+1+t138.*t244.*(t134+t125.*t149+t133.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1))).*(-t24-t49+t163+t191+t124.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0).*6.0e+1;
out1 = et6+et7+et8+et9+et10+et11+et12;
if nargout > 1
    et13 = a2.*t34.*t164.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^2-a2.*t34.*t191.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*1.0e+1-a2_d.*t34.*t124.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*2.0e+1-a2.*t34.*t47.*t124.*5.0+a2.*t34.*t46.*t163.*1.0e+1+a2.*t34.*t46.*t191.*1.0e+1-a2.*t34.*t124.*t146.*5.0-a2.*t34.*t124.*t184.*1.5e+1-a2.*t34.*t163.*t196.*1.0e+1-a2.*t34.*t191.*t196.*1.0e+1+a2_d.*t34.*t46.*t124.*2.0e+1-a2_d.*t34.*t47.*t123.*5.0-a2_d.*t34.*t45.*t163.*3.0e+1-a2_d.*t34.*t45.*t191.*3.0e+1-a2_d.*t34.*t123.*t146.*5.0-a2_d.*t34.*t123.*t184.*1.5e+1-a2_d.*t34.*t124.*t196.*2.0e+1-a2_d.*t34.*t163.*t179.*3.0e+1;
    et14 = a1_d.*t33.*t44.*u.*5.0+a1.*t33.*t44.*u_d.*5.0-a1_d.*t33.*t43.*u_d.*2.0e+1+a2.*t34.*t40.^5.*t123-a1.*t33.*t39.^5.*u+a1.*t13.*t33.*u_d.^3.*6.0e+1+a2.*t34.*t124.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*5.0+a2.*t34.*t123.*(t159+mu0_d.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1).*5.0)+a2_d.*t34.*t123.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*5.0-a2.*t34.*t40.*t123.*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*5.0+a2.*t34.*t46.*t124.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1-a2.*t34.*t47.*t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*5.0;
    et15 = a2.*t34.*t45.*t191.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*-3.0e+1-a2.*t34.*t123.*t184.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.5e+1-a2.*t34.*t124.*t196.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1-a2_d.*t34.*t45.*t124.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*6.0e+1+a2_d.*t34.*t46.*t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1+a2_d.*t34.*t40.*t191.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*6.0e+1;
    et16 = a2_d.*t34.*t124.*t179.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*-6.0e+1-a2_d.*t34.*t123.*t196.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1+a2.*t34.*t40.*t124.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*2.0e+1-a2.*t34.*t45.*t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*1.0e+1+a2_d.*t34.*t40.*t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*2.0e+1-a1.*kappa1_d.*t15.*t33.*t42.*6.0e+1+a1_d.*kappa1_d.*t9.*t15.*t33.*6.0e+1+a1_d.*kappa1_d.*t15.*t33.*t39.*1.2e+2+a2_d.*kappa2_d.*t34.*t163.*u_d.*6.0e+1+a2_d.*kappa2_d.*t34.*t191.*u_d.*6.0e+1-a2.*t14.*t15.*t34.*t124.*6.0e+1;
    et17 = a2.*t34.*t40.*t123.*t146.*5.0-a2.*t34.*t45.*t124.*t144.*3.0e+1+a2.*t34.*t40.*t123.*t184.*1.5e+1-a2.*t34.*t45.*t124.*t179.*3.0e+1+a2.*t34.*t40.*t124.*t196.*2.0e+1-a2.*t34.*t45.*t123.*t196.*1.0e+1+a2.*t34.*t40.*t163.*t179.*3.0e+1-a2.*t34.*t124.*t144.*t179.*3.0e+1-a2_d.*t14.*t15.*t34.*t123.*6.0e+1+a2_d.*t34.*t40.*t124.*t144.*6.0e+1+a2_d.*t34.*t40.*t124.*t179.*6.0e+1+a2_d.*t34.*t40.*t123.*t196.*2.0e+1+a1.*t9.*t33.*t43.*u_d.*2.0e+1-a1_d.*t9.*t33.*t42.*u_d.*6.0e+1+a2.*t34.*t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*(t152+mu0.*(t101+t104-t105-t22.*t30.*t35.*u.*2.4e+1)).*5.0+a2.*t14.*t15.*t34.*t40.*t123.*6.0e+1+a2.*kappa2_d.*t34.*t191.*u_d.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*6.0e+1;
    et18 = a2_d.*kappa2_d.*t34.*t124.*u_d.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.2e+2-a2.*t14.*t15.*t34.*t123.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*6.0e+1+a2.*t34.*t40.*t124.*t179.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*6.0e+1+a2.*t34.*t40.*t123.*t196.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*2.0e+1+a2.*kappa2_d.*t34.*t123.*u_d.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).^3.*2.0e+1-a1.*kappa1_d.*t9.*t15.*t33.*t39.*6.0e+1+a2.*kappa2_d.*t34.*t45.*t124.*u_d.*6.0e+1-a2.*kappa2_d.*t34.*t46.*t123.*u_d.*2.0e+1-a2.*kappa2_d.*t34.*t40.*t163.*u_d.*6.0e+1-a2.*kappa2_d.*t34.*t40.*t191.*u_d.*6.0e+1;
    et19 = a2.*kappa2_d.*t34.*t124.*t144.*u_d.*6.0e+1+a2.*kappa2_d.*t34.*t124.*t179.*u_d.*6.0e+1+a2.*kappa2_d.*t34.*t123.*t196.*u_d.*2.0e+1-a2_d.*kappa2_d.*t34.*t40.*t124.*u_d.*1.2e+2+a2_d.*kappa2_d.*t34.*t45.*t123.*u_d.*6.0e+1-a2.*kappa2_d.*t34.*t40.*t124.*u_d.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.2e+2+a2.*kappa2_d.*t34.*t45.*t123.*u_d.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*6.0e+1-a2_d.*kappa2_d.*t34.*t40.*t123.*u_d.*(mu0.*(t54+t56-tau1_d+t3.*t62)+mu0_d.*(t52-tau1)).*1.2e+2;
    out2 = et13+et14+et15+et16+et17+et18+et19;
end
end


function out1 = sym_barbarossa_tau_1_0(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_TAU_1_0
%    OUT1 = SYM_BARBAROSSA_TAU_1_0(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:47

out1 = tau1-(u.*(tau1-tau2))./(T+u);
end


function out1 = sym_barbarossa_tau_1_1(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_TAU_1_1
%    OUT1 = SYM_BARBAROSSA_TAU_1_1(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:47

t2 = T+u;
t3 = -tau2;
t4 = 1.0./t2;
t5 = t3+tau1;
out1 = tau1_d-t4.*t5.*u_d-t4.*u.*(tau1_d-tau2_d)+t4.^2.*t5.*u.*(T_d+u_d);
end


function out1 = sym_barbarossa_tau_1_2(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_TAU_1_2
%    OUT1 = SYM_BARBAROSSA_TAU_1_2(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:47

t2 = T+u;
t3 = T_d+u_d;
t4 = -tau2;
t5 = -tau2_d;
t6 = 1.0./t2.^2;
t7 = t4+tau1;
t8 = t5+tau1_d;
out1 = (t8.*u_d.*-2.0)./t2+t3.*t6.*t8.*u.*2.0+t3.*t6.*t7.*u_d.*2.0-1.0./t2.^3.*t3.^2.*t7.*u.*2.0;
end


function out1 = sym_barbarossa_tau_1_3(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_TAU_1_3
%    OUT1 = SYM_BARBAROSSA_TAU_1_3(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:47

t2 = T+u;
t3 = T_d+u_d;
t4 = -tau2;
t5 = -tau2_d;
t6 = t3.^2;
t7 = 1.0./t2.^3;
t8 = t4+tau1;
t9 = t5+tau1_d;
out1 = t6.*t7.*t9.*u.*-6.0-t6.*t7.*t8.*u_d.*6.0+1.0./t2.^2.*t3.*t9.*u_d.*6.0+1.0./t2.^4.*t3.^3.*t8.*u.*6.0;
end


function out1 = sym_barbarossa_tau_1_4(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_TAU_1_4
%    OUT1 = SYM_BARBAROSSA_TAU_1_4(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:47

t2 = T+u;
t3 = T_d+u_d;
t4 = -tau2;
t5 = -tau2_d;
t6 = t3.^3;
t7 = 1.0./t2.^4;
t8 = t4+tau1;
t9 = t5+tau1_d;
out1 = t6.*t7.*t9.*u.*2.4e+1+t6.*t7.*t8.*u_d.*2.4e+1-1.0./t2.^5.*t3.^4.*t8.*u.*2.4e+1-1.0./t2.^3.*t3.^2.*t9.*u_d.*2.4e+1;
end


function out1 = sym_barbarossa_tau_1_5(u,z,ut,zt,a1,a2,kappa1,kappa2,gam,delta,tau1,tau2,T,mu0,u_d,z_d,ut_d,zt_d,a1_d,a2_d,kappa1_d,kappa2_d,gam_d,delta_d,tau1_d,tau2_d,T_d,mu0_d)
%SYM_BARBAROSSA_TAU_1_5
%    OUT1 = SYM_BARBAROSSA_TAU_1_5(U,Z,UT,ZT,A1,A2,KAPPA1,KAPPA2,GAM,DELTA,TAU1,TAU2,T,MU0,U_D,Z_D,UT_D,ZT_D,A1_D,A2_D,KAPPA1_D,KAPPA2_D,GAM_D,DELTA_D,TAU1_D,TAU2_D,T_d,MU0_D)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    23-Sep-2026 16:42:47

t2 = T+u;
t3 = T_d+u_d;
t4 = -tau2;
t5 = -tau2_d;
t6 = t3.^4;
t7 = 1.0./t2.^5;
t8 = t4+tau1;
t9 = t5+tau1_d;
out1 = t6.*t7.*t9.*u.*-1.2e+2-t6.*t7.*t8.*u_d.*1.2e+2+1.0./t2.^6.*t3.^5.*t8.*u.*1.2e+2+1.0./t2.^4.*t3.^3.*t9.*u_d.*1.2e+2;
end

